version: "3"
name: "test-local"
services:
  test:
    container_name: test-local
    image: test-local
    build:
      context: ../../../
      dockerfile: ci/docker/dockerfiles/Dockerfile
      target: local
    ports:
      - "${APP_DOCKER_HOST_PORT}:${PORT}"
    volumes:
      - ../../../:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: test-local-postgres
    image: test-postgres
    build:
      context: ../../../
      dockerfile: ci/docker/dockerfiles/Dockerfile.postgre
    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DOCKER_HOST_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      interval: 5s
      start_period: 5s
      retries: 5
